spring:
  application:
    name: leader-demo
  cloud:
    kubernetes:
      config:
        enabled: false
      secrets:
        enabled: false
      leader:
        enabled: true
        role: leader-demo
        config-map-namespace: default

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    com.example.leaderdemo: INFO
    org.springframework.cloud.kubernetes: INFO
